### ISSUE TITLE
Calculating lengths

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/assignments#1]
Professor,

To calculate a document's length, we necessarily need to know all of the terms that it occurs in. As the index comes sorted by term and not document, my guess is that we have to go through the whole index checking if each term has the document or not (which would in turn mean that we have to iterate through each list). Is there a more efficient way of doing this in python?

**Comment by aronwc** [comment]
That's correct, though in one loop through the index, you should calculate the lengths of all documents.
