### ISSUE TITLE
Bonus Assignment: prune method

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/assignments#11]
Hi Prof,
Could you please elaborate more on prune method ? It seems more diffucult to implement provided complete code runs in < 30 seconds.  
Any suggestions on how to prune?

**Comment by aronwc** [comment]
1. Count document frequency for each term.
2. Create a pruned vocabulary of  terms with frequency greater than or equal to threshold.
3. Loop through all dicts removing terms not on this pruned vocab.

**Comment by changediyasunny** [comment]
Okay. I will try on making it more efficient.
Thanks Prof.
