### ISSUE TITLE
Bonus Assignment: Initialize K mean vector to be first k-docs

### ISSUE THREAD

**Issue by changediyasunny** [iit-cs429/assignments#12]
Prof.,
step 1: says that "initialize means" ? what this actually means ? 
It is said that "k mean vectors to be the first k documents provided." so we have "k".

**Comment by changediyasunny** [comment]
because we have docs in the form of "docs={Counter('a':3,'b':2,'c':4), ...} " Do we have to calculate geometric mean of all values? and represent it as mean vector?

**Comment by aronwc** [comment]
Please read the book for more on K-Means.

The first k documents should be copied to become the "means" of each cluster. In subsequent iterations, these means will be recalculated, according to the algorithm.
