### ISSUE TITLE
Value of recall in the doctests

### ISSUE THREAD

**Issue by sshenoy6** [iit-cs429/assignments#3]
For A2: In the evaluate.py file ,the value of Recall is calculated in the doctests as 0.5. 

I think it should be 0.1 as tp value is 1 and fn is 9 (taking top 10 documents). So it would be 1/10 = 0.1 and not 0.5.

Am I going wrong in the calculation here?

**Comment by aronwc** [comment]
The doctest is correct. 

``` python
Recall().evaluate([1, 2, 3, 4], [2, 5])
```

There are 2 documents relevant to the query (2 and 5). The search engine returned one of them (2). So, recall is 1/2 (tp / (tp + fn) = 1 / (1 + 1)). The only false negative is document 5 (it should have been returned, but wasn't).

The precision here is 1/4. Of the four documents returned ([1,2,3,4]), only one was relevant.

Best,
Aron

**Comment by sshenoy6** [comment]
Thanks for the clarification professor. It is clear now.
